from __future__ import annotations

translations = {
    # Customer buttons
    "customer.ask_ai": "🤖 Ask AI",
    "customer.contact_manager": "👨‍💼 Contact Manager",
    "customer.broadcasts_on": "🔔 Broadcasts: ON",
    "customer.broadcasts_off": "🔕 Broadcasts: OFF",
    "customer.cancel": "❌ Cancel",
    "customer.cancel_request": "❌ Cancel Request",
    "customer.close_chat": "✅ Close Chat",
    
    # Manager buttons
    "manager.new_tickets": "📥 New Tickets",
    "manager.active_chats": "💬 Active Chats",
    "manager.stats": "📊 My Statistics",
    "manager.notifications_on": "🔔 Notifications: ON",
    "manager.notifications_off": "🔕 Notifications: OFF",
    "manager.close_ticket": "🔒 Close Ticket",
    "manager.exit_reply": "⏸ Exit Reply Mode",
    "manager.my_dialogs": "↩️ My Dialogs",
    
    # Owner buttons
    "owner.choose_model": "🤖 Choose AI Model",
    "owner.stats": "📊 Statistics",
    "owner.tickets": "📂 Tickets",
    "owner.broadcast": "📨 Broadcast",
    "owner.broadcast_history": "📋 Broadcast History",
    "owner.managers": "👨‍💼 Managers",
    "owner.promote_manager": "➕ Assign Manager",
    "owner.manager_stats": "📊 Manager Stats",
    "owner.cancel": "❌ Cancel",
    "owner.back": "↩️ Back",
    
    # Bot UI strings
    "bot.welcome": "Welcome to Support! Please select an option.",
    "bot.language_btn": "🌐 Language / Язык / Тил",
    "bot.choose_language": "Select language / Choose language / Тилди тандаңыз:",
    "bot.language_switched": "Language changed to English 🇺🇸",
    "bot.open_miniapp": "💬 Open Mini App",
    
    # Ticket actions
    "ticket.cancel_confirm": "Confirm request cancellation.",
    "ticket.close_confirm": "Confirm closing support thread.",
    "ticket.closed_by_customer": "Dialog closed by customer.",
    "ticket.closed_by_manager": "Ticket #{id} closed by manager.",
    "ticket.closed_by_supervisor": "Ticket #{id} closed by supervisor.",
    "ticket.claimed": "Manager {name} claimed your ticket #{id}.",
    "ticket.created": "Ticket #{id} created. Please wait for a manager to reply.",
    "ticket.no_active": "You have no active support requests.",
    "ticket.already_active": "You already have an active support request.",
    "ticket.open_dialog": "💬 Open Dialog",
    "ticket.history": "👁 History",
    "ticket.claim": "✅ Claim Ticket",
    "ticket.open_id": "💬 Open #{id}",
    "ticket.close_yes": "Yes, close",
    
    # AI Messages
    "ai.thinking": "⏳ Thinking...",
    "ai.warn_unverified": "⚠️ The response is generated by AI assistant and may be inaccurate.",
    
    # Broadcast Flow
    "broadcast.enter_content": "Please send the message you want to broadcast. Photo, video, and text are supported.",
    "broadcast.choosing_buttons": "Select buttons for the broadcast:",
    "broadcast.preview": "Broadcast preview:",
    "broadcast.confirm": "Confirm sending broadcast to {count} users.",
    "broadcast.sending": "Broadcast started. This may take some time...",
    "broadcast.completed": "Broadcast #{id} completed!\nDelivered: {delivered}\nFailed: {failed}\nBlocked: {blocked}",
    "broadcast.cancelled": "Broadcast cancelled.",
    
    # Broadcast formatting specific keys
    "broadcast.recipients": "Recipients",
    "broadcast.message_preview": "Message",
    "broadcast.buttons": "Buttons",
    "broadcast.confirm_title": "Confirm mass broadcast.",
    "broadcast.confirm_footer": "After confirmation, the message will be sent to clients.",

    # Owner specific UI labels
    "owner.model_selection": "Choose AI model\nActive model: {model}",
    "owner.normal_panel": "Owner panel\nActive model: {model}",
    
    # Menu flow screens
    "manager.main_menu": "Manager panel is open. Select an action.",
    "customer.requesting": "Describe your question in one message or attach a photo, video or document. A manager will see your ticket.",
    "customer.waiting": "You already have an active ticket. Waiting for an available manager. You can send additional messages or files.",
    "customer.chatting": "A manager is connected. Write a message in this chat.",
    "customer.ai_chat_welcome": "Hello! I am the company's AI assistant. Write a question or select an action.",
    
    # Common strings
    "common.error": "An error occurred.",
    "common.back": "Back",
    "common.cancel": "Cancel",
    "common.yes": "Yes",
    "common.no": "No",
    "common.saved": "Saved.",
    "common.additional_options": "Additional options:",
    
    # Ticket chat view text
    "ticket.chat_text": "You are replying to the client on ticket #{id}. All messages and files sent now will be forwarded to this client.\n\nClient: {client}\nStatus: {status}\n\nRecent messages:\n{history}",
    "ticket.chat_empty": "Ticket history is empty.",
    "ticket.status_claimed": "In progress",
    "ticket.status_open": "Open",

    # Inline Keyboards
    "inline.cancel_yes": "Yes, cancel",
    "inline.cancel_no": "No",
    "inline.claim_ticket": "✅ Claim Ticket",
    "inline.history": "👁 History",
    "inline.close_question": "🔒 Close Ticket",
    "inline.exit_reply": "⏸ Exit Reply Mode",
    "inline.my_dialogs": "↩️ My Dialogs",
    "inline.open_dialog": "💬 Open Dialog",
    "inline.turn_off_notify": "Turn off notifications",
    "inline.turn_on_notify": "Turn on notifications",
    "inline.go_back": "⬅️ Back",
    "inline.open_ticket_id": "💬 Open #{id}",
    "inline.no_buttons": "No Buttons",
    "inline.official_site": "Official Site",
    "inline.both_buttons": "Instagram + Site",
    "inline.send_test_me": "🧪 Send test to me",
    "inline.send_all": "✅ Send to all",
    "inline.create_new": "✏️ Create again",
    "inline.confirm_send": "✅ Confirm sending",
    "inline.open_report": "Open report",
    "inline.disable_manager": "❌ Deactivate",
    "inline.enable_manager": "✅ Activate",
    "inline.disable_manager_confirm": "Yes, deactivate",
    "inline.promote_confirm": "Yes, assign",
}
