"""add_staff_table

Revision ID: 0beb440e2311
Revises: 202605290003
Create Date: 2026-05-30 17:56:30.679412
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0beb440e2311'
down_revision = '202605290003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    op.create_index(op.f('ix_staff_telegram_user_id'), 'staff', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_telegram_user_id'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###

