"""refactor_staff_members

Revision ID: 49f843f9c6b8
Revises: 0beb440e2311
Create Date: 2026-05-30 18:04:46.480123
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '49f843f9c6b8'
down_revision = '0beb440e2311'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('added_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_members_telegram_user_id'), 'staff_members', ['telegram_user_id'], unique=True)
    
    # Safely migrate data from staff to staff_members if it exists
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'staff' in tables:
        staff_table = sa.table(
            'staff',
            sa.column('telegram_user_id', sa.BigInteger),
            sa.column('is_active', sa.Boolean),
            sa.column('created_at', sa.DateTime),
            sa.column('disabled_at', sa.DateTime),
            sa.column('added_by_telegram_id', sa.BigInteger),
            sa.column('notes', sa.Text)
        )
        
        staff_members_table = sa.table(
            'staff_members',
            sa.column('telegram_user_id', sa.BigInteger),
            sa.column('role', sa.String),
            sa.column('status', sa.String),
            sa.column('added_by_telegram_id', sa.BigInteger),
            sa.column('added_at', sa.DateTime),
            sa.column('disabled_at', sa.DateTime),
            sa.column('notes', sa.Text)
        )
        
        results = bind.execute(sa.select(staff_table)).all()
        for row in results:
            status_val = "active" if row.is_active else "disabled"
            bind.execute(
                staff_members_table.insert().values(
                    telegram_user_id=row.telegram_user_id,
                    role="manager",
                    status=status_val,
                    added_by_telegram_id=row.added_by_telegram_id,
                    added_at=row.created_at,
                    disabled_at=row.disabled_at,
                    notes=row.notes
                )
            )
        
        # Now drop the old staff table
        # Check if index exists first
        indexes = [idx['name'] for idx in inspector.get_indexes('staff')]
        if 'ix_staff_telegram_user_id' in indexes:
            op.drop_index('ix_staff_telegram_user_id', table_name='staff')
        op.drop_table('staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('telegram_user_id', sa.BIGINT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.func.now(), nullable=False),
    sa.Column('disabled_at', sa.DATETIME(), nullable=True),
    sa.Column('added_by_telegram_id', sa.BIGINT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    op.create_index(op.f('ix_staff_telegram_user_id'), 'staff', ['telegram_user_id'], unique=False)
    op.drop_index(op.f('ix_staff_members_telegram_user_id'), table_name='staff_members')
    op.drop_table('staff_members')
    # ### end Alembic commands ###

